""" Loads GUFO data used for the evaluations. """

# TODO (@pedropaulofb): The data should be loaded from a structured input file, like a csv, JSON, or YAML file.

if __name__ != "__main__":
    from modules.dataclass_definitions import GUFOClass


    def get_list_of_gufo_types():
        """Returns a list of dataclass GUFOClass with all GUFO types and its corresponding internal list elements"""

        gufo_types = []
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#AntiRigidType",
                                    is_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                             "http://purl.org/nemo/gufo#NonRigidType"],
                                    can_list=["http://purl.org/nemo/gufo#NonSortal", "http://purl.org/nemo/gufo#Phase",
                                              "http://purl.org/nemo/gufo#PhaseMixin", "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#Sortal"],
                                    not_list=["http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                              "http://purl.org/nemo/gufo#Mixin", "http://purl.org/nemo/gufo#RigidType",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#Category",
                                    is_list=["http://purl.org/nemo/gufo#Category",
                                             "http://purl.org/nemo/gufo#NonSortal",
                                             "http://purl.org/nemo/gufo#RigidType"],
                                    can_list=["http://purl.org/nemo/gufo#Kind", "http://purl.org/nemo/gufo#SubKind"],
                                    not_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                              "http://purl.org/nemo/gufo#Mixin",
                                              "http://purl.org/nemo/gufo#NonRigidType",
                                              "http://purl.org/nemo/gufo#Phase", "http://purl.org/nemo/gufo#PhaseMixin",
                                              "http://purl.org/nemo/gufo#Role", "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#Sortal"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#Kind",
                                    is_list=["http://purl.org/nemo/gufo#Kind", "http://purl.org/nemo/gufo#RigidType",
                                             "http://purl.org/nemo/gufo#Sortal"], can_list=[],
                                    not_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                              "http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Mixin",
                                              "http://purl.org/nemo/gufo#NonRigidType",
                                              "http://purl.org/nemo/gufo#NonSortal", "http://purl.org/nemo/gufo#Phase",
                                              "http://purl.org/nemo/gufo#PhaseMixin", "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#Mixin",
                                    is_list=["http://purl.org/nemo/gufo#Mixin",
                                             "http://purl.org/nemo/gufo#NonRigidType",
                                             "http://purl.org/nemo/gufo#NonSortal",
                                             "http://purl.org/nemo/gufo#SemiRigidType"],
                                    can_list=[], not_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                                           "http://purl.org/nemo/gufo#Category",
                                                           "http://purl.org/nemo/gufo#Kind",
                                                           "http://purl.org/nemo/gufo#Phase",
                                                           "http://purl.org/nemo/gufo#PhaseMixin",
                                                           "http://purl.org/nemo/gufo#RigidType",
                                                           "http://purl.org/nemo/gufo#Role",
                                                           "http://purl.org/nemo/gufo#RoleMixin",
                                                           "http://purl.org/nemo/gufo#Sortal",
                                                           "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(
            GUFOClass(uri="http://purl.org/nemo/gufo#NonRigidType", is_list=["http://purl.org/nemo/gufo#NonRigidType"],
                      can_list=["http://purl.org/nemo/gufo#AntiRigidType", "http://purl.org/nemo/gufo#Mixin",
                                "http://purl.org/nemo/gufo#NonSortal", "http://purl.org/nemo/gufo#Phase",
                                "http://purl.org/nemo/gufo#PhaseMixin", "http://purl.org/nemo/gufo#Role",
                                "http://purl.org/nemo/gufo#RoleMixin", "http://purl.org/nemo/gufo#SemiRigidType",
                                "http://purl.org/nemo/gufo#Sortal"],
                      not_list=["http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                "http://purl.org/nemo/gufo#RigidType", "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(
            GUFOClass(uri="http://purl.org/nemo/gufo#NonSortal", is_list=["http://purl.org/nemo/gufo#NonSortal"],
                      can_list=["http://purl.org/nemo/gufo#AntiRigidType", "http://purl.org/nemo/gufo#Category",
                                "http://purl.org/nemo/gufo#Mixin", "http://purl.org/nemo/gufo#NonRigidType",
                                "http://purl.org/nemo/gufo#PhaseMixin", "http://purl.org/nemo/gufo#RigidType",
                                "http://purl.org/nemo/gufo#RoleMixin", "http://purl.org/nemo/gufo#SemiRigidType"],
                      not_list=["http://purl.org/nemo/gufo#Kind", "http://purl.org/nemo/gufo#Phase",
                                "http://purl.org/nemo/gufo#Role", "http://purl.org/nemo/gufo#Sortal",
                                "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#Phase",
                                    is_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                             "http://purl.org/nemo/gufo#NonRigidType",
                                             "http://purl.org/nemo/gufo#Phase", "http://purl.org/nemo/gufo#Sortal"],
                                    can_list=[],
                                    not_list=["http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                              "http://purl.org/nemo/gufo#Mixin", "http://purl.org/nemo/gufo#NonSortal",
                                              "http://purl.org/nemo/gufo#PhaseMixin",
                                              "http://purl.org/nemo/gufo#RigidType", "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#PhaseMixin",
                                    is_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                             "http://purl.org/nemo/gufo#NonRigidType",
                                             "http://purl.org/nemo/gufo#NonSortal",
                                             "http://purl.org/nemo/gufo#PhaseMixin"],
                                    can_list=["http://purl.org/nemo/gufo#Category",
                                              "http://purl.org/nemo/gufo#RigidType"],
                                    not_list=["http://purl.org/nemo/gufo#Kind", "http://purl.org/nemo/gufo#Mixin",
                                              "http://purl.org/nemo/gufo#Phase", "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#Sortal", "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(
            GUFOClass(uri="http://purl.org/nemo/gufo#RigidType", is_list=["http://purl.org/nemo/gufo#RigidType"],
                      can_list=["http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                "http://purl.org/nemo/gufo#NonSortal", "http://purl.org/nemo/gufo#Sortal",
                                "http://purl.org/nemo/gufo#SubKind"],
                      not_list=["http://purl.org/nemo/gufo#AntiRigidType", "http://purl.org/nemo/gufo#Mixin",
                                "http://purl.org/nemo/gufo#NonRigidType", "http://purl.org/nemo/gufo#Phase",
                                "http://purl.org/nemo/gufo#PhaseMixin", "http://purl.org/nemo/gufo#Role",
                                "http://purl.org/nemo/gufo#RoleMixin", "http://purl.org/nemo/gufo#SemiRigidType"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#Role",
                                    is_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                             "http://purl.org/nemo/gufo#NonRigidType", "http://purl.org/nemo/gufo#Role",
                                             "http://purl.org/nemo/gufo#Sortal"], can_list=[],
                                    not_list=["http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                              "http://purl.org/nemo/gufo#Mixin", "http://purl.org/nemo/gufo#NonSortal",
                                              "http://purl.org/nemo/gufo#Phase", "http://purl.org/nemo/gufo#PhaseMixin",
                                              "http://purl.org/nemo/gufo#RigidType",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#RoleMixin",
                                    is_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                             "http://purl.org/nemo/gufo#NonRigidType",
                                             "http://purl.org/nemo/gufo#NonSortal",
                                             "http://purl.org/nemo/gufo#RoleMixin"],
                                    can_list=["http://purl.org/nemo/gufo#Category",
                                              "http://purl.org/nemo/gufo#RigidType"],
                                    not_list=["http://purl.org/nemo/gufo#Kind", "http://purl.org/nemo/gufo#Mixin",
                                              "http://purl.org/nemo/gufo#Phase", "http://purl.org/nemo/gufo#PhaseMixin",
                                              "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#SemiRigidType",
                                              "http://purl.org/nemo/gufo#Sortal", "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#SemiRigidType",
                                    is_list=["http://purl.org/nemo/gufo#NonRigidType",
                                             "http://purl.org/nemo/gufo#SemiRigidType"],
                                    can_list=["http://purl.org/nemo/gufo#Mixin", "http://purl.org/nemo/gufo#NonSortal",
                                              "http://purl.org/nemo/gufo#Sortal"],
                                    not_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                              "http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                              "http://purl.org/nemo/gufo#Phase", "http://purl.org/nemo/gufo#PhaseMixin",
                                              "http://purl.org/nemo/gufo#RigidType", "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SubKind"]))
        gufo_types.append(
            GUFOClass(uri="http://purl.org/nemo/gufo#Sortal", is_list=["http://purl.org/nemo/gufo#Sortal"],
                      can_list=["http://purl.org/nemo/gufo#AntiRigidType", "http://purl.org/nemo/gufo#Kind",
                                "http://purl.org/nemo/gufo#NonRigidType", "http://purl.org/nemo/gufo#Phase",
                                "http://purl.org/nemo/gufo#RigidType", "http://purl.org/nemo/gufo#Role",
                                "http://purl.org/nemo/gufo#SemiRigidType", "http://purl.org/nemo/gufo#SubKind"],
                      not_list=["http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Mixin",
                                "http://purl.org/nemo/gufo#NonSortal", "http://purl.org/nemo/gufo#PhaseMixin",
                                "http://purl.org/nemo/gufo#RoleMixin"]))
        gufo_types.append(GUFOClass(uri="http://purl.org/nemo/gufo#SubKind",
                                    is_list=["http://purl.org/nemo/gufo#RigidType", "http://purl.org/nemo/gufo#Sortal",
                                             "http://purl.org/nemo/gufo#SubKind"], can_list=[],
                                    not_list=["http://purl.org/nemo/gufo#AntiRigidType",
                                              "http://purl.org/nemo/gufo#Category", "http://purl.org/nemo/gufo#Kind",
                                              "http://purl.org/nemo/gufo#Mixin",
                                              "http://purl.org/nemo/gufo#NonRigidType",
                                              "http://purl.org/nemo/gufo#NonSortal", "http://purl.org/nemo/gufo#Phase",
                                              "http://purl.org/nemo/gufo#PhaseMixin", "http://purl.org/nemo/gufo#Role",
                                              "http://purl.org/nemo/gufo#RoleMixin",
                                              "http://purl.org/nemo/gufo#SemiRigidType"]))
        return gufo_types


    def get_list_of_gufo_individuals():
        """Returns a list of dataclass GUFOClass with all GUFO invididuals and its corresponding internal list elem."""

        gufo_individuals = []
        gufo_individuals.append(
            GUFOClass(uri="http://purl.org/nemo/gufo#Aspect", is_list=["http://purl.org/nemo/gufo#Aspect"],
                      can_list=["http://purl.org/nemo/gufo#ExtrinsicAspect", "http://purl.org/nemo/gufo#ExtrinsicMode",
                                "http://purl.org/nemo/gufo#IntrinsicAspect", "http://purl.org/nemo/gufo#IntrinsicMode",
                                "http://purl.org/nemo/gufo#Quality", "http://purl.org/nemo/gufo#Relator"],
                      not_list=["http://purl.org/nemo/gufo#Collection", "http://purl.org/nemo/gufo#FixedCollection",
                                "http://purl.org/nemo/gufo#FunctionalComplex", "http://purl.org/nemo/gufo#Object",
                                "http://purl.org/nemo/gufo#Quantity", "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#Collection",
                                          is_list=["http://purl.org/nemo/gufo#Collection",
                                                   "http://purl.org/nemo/gufo#Object"],
                                          can_list=["http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#VariableCollection"],
                                          not_list=["http://purl.org/nemo/gufo#Aspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#Relator"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#ExtrinsicAspect",
                                          is_list=["http://purl.org/nemo/gufo#Aspect",
                                                   "http://purl.org/nemo/gufo#ExtrinsicAspect"],
                                          can_list=["http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#Relator"],
                                          not_list=["http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Object",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#ExtrinsicMode",
                                          is_list=["http://purl.org/nemo/gufo#Aspect",
                                                   "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                   "http://purl.org/nemo/gufo#ExtrinsicMode"],
                                          can_list=["http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality"],
                                          not_list=["http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#Object",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#Relator",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#FixedCollection",
                                          is_list=["http://purl.org/nemo/gufo#Collection",
                                                   "http://purl.org/nemo/gufo#FixedCollection",
                                                   "http://purl.org/nemo/gufo#Object"],
                                          can_list=["http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Relator"],
                                          not_list=["http://purl.org/nemo/gufo#Aspect",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#FunctionalComplex",
                                          is_list=["http://purl.org/nemo/gufo#FunctionalComplex",
                                                   "http://purl.org/nemo/gufo#Object"],
                                          can_list=["http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#VariableCollection"],
                                          not_list=["http://purl.org/nemo/gufo#Aspect",
                                                    "http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#Relator"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#IntrinsicAspect",
                                          is_list=["http://purl.org/nemo/gufo#Aspect",
                                                   "http://purl.org/nemo/gufo#IntrinsicAspect"],
                                          can_list=["http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Relator"],
                                          not_list=["http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#Object",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#IntrinsicMode",
                                          is_list=["http://purl.org/nemo/gufo#Aspect",
                                                   "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                   "http://purl.org/nemo/gufo#IntrinsicMode"], can_list=[],
                                          not_list=["http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#Object",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#Relator",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(
            GUFOClass(uri="http://purl.org/nemo/gufo#Object", is_list=["http://purl.org/nemo/gufo#Object"],
                      can_list=["http://purl.org/nemo/gufo#Collection", "http://purl.org/nemo/gufo#FixedCollection",
                                "http://purl.org/nemo/gufo#FunctionalComplex", "http://purl.org/nemo/gufo#Quantity",
                                "http://purl.org/nemo/gufo#VariableCollection"],
                      not_list=["http://purl.org/nemo/gufo#Aspect", "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                "http://purl.org/nemo/gufo#ExtrinsicMode", "http://purl.org/nemo/gufo#IntrinsicAspect",
                                "http://purl.org/nemo/gufo#IntrinsicMode", "http://purl.org/nemo/gufo#Quality",
                                "http://purl.org/nemo/gufo#Relator"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#Quality",
                                          is_list=["http://purl.org/nemo/gufo#Aspect",
                                                   "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                   "http://purl.org/nemo/gufo#Quality"], can_list=[],
                                          not_list=["http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Object",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#Relator",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#Quantity",
                                          is_list=["http://purl.org/nemo/gufo#Object",
                                                   "http://purl.org/nemo/gufo#Quantity"],
                                          can_list=["http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#VariableCollection"],
                                          not_list=["http://purl.org/nemo/gufo#Aspect",
                                                    "http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Relator"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#Relator",
                                          is_list=["http://purl.org/nemo/gufo#Aspect",
                                                   "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                   "http://purl.org/nemo/gufo#Relator"],
                                          can_list=["http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality"],
                                          not_list=["http://purl.org/nemo/gufo#Collection",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#Object",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#VariableCollection"]))
        gufo_individuals.append(GUFOClass(uri="http://purl.org/nemo/gufo#VariableCollection",
                                          is_list=["http://purl.org/nemo/gufo#Collection",
                                                   "http://purl.org/nemo/gufo#Object",
                                                   "http://purl.org/nemo/gufo#VariableCollection"], can_list=[],
                                          not_list=["http://purl.org/nemo/gufo#Aspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicAspect",
                                                    "http://purl.org/nemo/gufo#ExtrinsicMode",
                                                    "http://purl.org/nemo/gufo#FixedCollection",
                                                    "http://purl.org/nemo/gufo#FunctionalComplex",
                                                    "http://purl.org/nemo/gufo#IntrinsicAspect",
                                                    "http://purl.org/nemo/gufo#IntrinsicMode",
                                                    "http://purl.org/nemo/gufo#Quality",
                                                    "http://purl.org/nemo/gufo#Quantity",
                                                    "http://purl.org/nemo/gufo#Relator"]))
        return gufo_individuals
